/* tslint:disable */
/* eslint-disable */
/**
 * notifications
 * This app provides a backend and frontend for the notification API available in Nextcloud.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { EndpointDeleteAllNotifications200ResponseOcs } from './EndpointDeleteAllNotifications200ResponseOcs.ts';
import {
    EndpointDeleteAllNotifications200ResponseOcsFromJSON,
    EndpointDeleteAllNotifications200ResponseOcsFromJSONTyped,
    EndpointDeleteAllNotifications200ResponseOcsToJSON,
} from './EndpointDeleteAllNotifications200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface EndpointDeleteAllNotifications200Response
 */
export interface EndpointDeleteAllNotifications200Response {
    /**
     * 
     * @type {EndpointDeleteAllNotifications200ResponseOcs}
     * @memberof EndpointDeleteAllNotifications200Response
     */
    ocs: EndpointDeleteAllNotifications200ResponseOcs;
}

/**
 * Check if a given object implements the EndpointDeleteAllNotifications200Response interface.
 */
export function instanceOfEndpointDeleteAllNotifications200Response(value: object): value is EndpointDeleteAllNotifications200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function EndpointDeleteAllNotifications200ResponseFromJSON(json: any): EndpointDeleteAllNotifications200Response {
    return EndpointDeleteAllNotifications200ResponseFromJSONTyped(json, false);
}

export function EndpointDeleteAllNotifications200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndpointDeleteAllNotifications200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': EndpointDeleteAllNotifications200ResponseOcsFromJSON(json['ocs']),
    };
}

export function EndpointDeleteAllNotifications200ResponseToJSON(value?: EndpointDeleteAllNotifications200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': EndpointDeleteAllNotifications200ResponseOcsToJSON(value['ocs']),
    };
}

