/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { BanUnbanActor200ResponseOcs } from './BanUnbanActor200ResponseOcs.ts';
import {
    BanUnbanActor200ResponseOcsFromJSON,
    BanUnbanActor200ResponseOcsFromJSONTyped,
    BanUnbanActor200ResponseOcsToJSON,
} from './BanUnbanActor200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface BanUnbanActor200Response
 */
export interface BanUnbanActor200Response {
    /**
     * 
     * @type {BanUnbanActor200ResponseOcs}
     * @memberof BanUnbanActor200Response
     */
    ocs: BanUnbanActor200ResponseOcs;
}

/**
 * Check if a given object implements the BanUnbanActor200Response interface.
 */
export function instanceOfBanUnbanActor200Response(value: object): value is BanUnbanActor200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function BanUnbanActor200ResponseFromJSON(json: any): BanUnbanActor200Response {
    return BanUnbanActor200ResponseFromJSONTyped(json, false);
}

export function BanUnbanActor200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BanUnbanActor200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': BanUnbanActor200ResponseOcsFromJSON(json['ocs']),
    };
}

export function BanUnbanActor200ResponseToJSON(value?: BanUnbanActor200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': BanUnbanActor200ResponseOcsToJSON(value['ocs']),
    };
}

