/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { CallJoinCall400ResponseOcs } from './CallJoinCall400ResponseOcs.ts';
import {
    CallJoinCall400ResponseOcsFromJSON,
    CallJoinCall400ResponseOcsFromJSONTyped,
    CallJoinCall400ResponseOcsToJSON,
} from './CallJoinCall400ResponseOcs.ts';

/**
 * 
 * @export
 * @interface CallJoinCall400Response
 */
export interface CallJoinCall400Response {
    /**
     * 
     * @type {CallJoinCall400ResponseOcs}
     * @memberof CallJoinCall400Response
     */
    ocs: CallJoinCall400ResponseOcs;
}

/**
 * Check if a given object implements the CallJoinCall400Response interface.
 */
export function instanceOfCallJoinCall400Response(value: object): value is CallJoinCall400Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function CallJoinCall400ResponseFromJSON(json: any): CallJoinCall400Response {
    return CallJoinCall400ResponseFromJSONTyped(json, false);
}

export function CallJoinCall400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallJoinCall400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': CallJoinCall400ResponseOcsFromJSON(json['ocs']),
    };
}

export function CallJoinCall400ResponseToJSON(value?: CallJoinCall400Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': CallJoinCall400ResponseOcsToJSON(value['ocs']),
    };
}

