/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface CapabilitiesConfigFederation
 */
export interface CapabilitiesConfigFederation {
    /**
     * 
     * @type {boolean}
     * @memberof CapabilitiesConfigFederation
     */
    enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CapabilitiesConfigFederation
     */
    incomingEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CapabilitiesConfigFederation
     */
    outgoingEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CapabilitiesConfigFederation
     */
    onlyTrustedServers: boolean;
}

/**
 * Check if a given object implements the CapabilitiesConfigFederation interface.
 */
export function instanceOfCapabilitiesConfigFederation(value: object): value is CapabilitiesConfigFederation {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('incomingEnabled' in value) || value['incomingEnabled'] === undefined) return false;
    if (!('outgoingEnabled' in value) || value['outgoingEnabled'] === undefined) return false;
    if (!('onlyTrustedServers' in value) || value['onlyTrustedServers'] === undefined) return false;
    return true;
}

export function CapabilitiesConfigFederationFromJSON(json: any): CapabilitiesConfigFederation {
    return CapabilitiesConfigFederationFromJSONTyped(json, false);
}

export function CapabilitiesConfigFederationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CapabilitiesConfigFederation {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'incomingEnabled': json['incoming-enabled'],
        'outgoingEnabled': json['outgoing-enabled'],
        'onlyTrustedServers': json['only-trusted-servers'],
    };
}

export function CapabilitiesConfigFederationToJSON(value?: CapabilitiesConfigFederation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'enabled': value['enabled'],
        'incoming-enabled': value['incomingEnabled'],
        'outgoing-enabled': value['outgoingEnabled'],
        'only-trusted-servers': value['onlyTrustedServers'],
    };
}

