/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { OCSMeta } from './OCSMeta.ts';
import {
    OCSMetaFromJSON,
    OCSMetaFromJSONTyped,
    OCSMetaToJSON,
} from './OCSMeta.ts';
import type { FilesIntegrationGetRoomByShareToken200ResponseOcsData } from './FilesIntegrationGetRoomByShareToken200ResponseOcsData.ts';
import {
    FilesIntegrationGetRoomByShareToken200ResponseOcsDataFromJSON,
    FilesIntegrationGetRoomByShareToken200ResponseOcsDataFromJSONTyped,
    FilesIntegrationGetRoomByShareToken200ResponseOcsDataToJSON,
} from './FilesIntegrationGetRoomByShareToken200ResponseOcsData.ts';

/**
 * 
 * @export
 * @interface FilesIntegrationGetRoomByShareToken200ResponseOcs
 */
export interface FilesIntegrationGetRoomByShareToken200ResponseOcs {
    /**
     * 
     * @type {OCSMeta}
     * @memberof FilesIntegrationGetRoomByShareToken200ResponseOcs
     */
    meta: OCSMeta;
    /**
     * 
     * @type {FilesIntegrationGetRoomByShareToken200ResponseOcsData}
     * @memberof FilesIntegrationGetRoomByShareToken200ResponseOcs
     */
    data: FilesIntegrationGetRoomByShareToken200ResponseOcsData;
}

/**
 * Check if a given object implements the FilesIntegrationGetRoomByShareToken200ResponseOcs interface.
 */
export function instanceOfFilesIntegrationGetRoomByShareToken200ResponseOcs(value: object): value is FilesIntegrationGetRoomByShareToken200ResponseOcs {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FilesIntegrationGetRoomByShareToken200ResponseOcsFromJSON(json: any): FilesIntegrationGetRoomByShareToken200ResponseOcs {
    return FilesIntegrationGetRoomByShareToken200ResponseOcsFromJSONTyped(json, false);
}

export function FilesIntegrationGetRoomByShareToken200ResponseOcsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilesIntegrationGetRoomByShareToken200ResponseOcs {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': OCSMetaFromJSON(json['meta']),
        'data': FilesIntegrationGetRoomByShareToken200ResponseOcsDataFromJSON(json['data']),
    };
}

export function FilesIntegrationGetRoomByShareToken200ResponseOcsToJSON(value?: FilesIntegrationGetRoomByShareToken200ResponseOcs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'meta': OCSMetaToJSON(value['meta']),
        'data': FilesIntegrationGetRoomByShareToken200ResponseOcsDataToJSON(value['data']),
    };
}

