/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { FilesIntegrationGetRoomByShareToken200ResponseOcs } from './FilesIntegrationGetRoomByShareToken200ResponseOcs.ts';
import {
    FilesIntegrationGetRoomByShareToken200ResponseOcsFromJSON,
    FilesIntegrationGetRoomByShareToken200ResponseOcsFromJSONTyped,
    FilesIntegrationGetRoomByShareToken200ResponseOcsToJSON,
} from './FilesIntegrationGetRoomByShareToken200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface FilesIntegrationGetRoomByShareToken200Response
 */
export interface FilesIntegrationGetRoomByShareToken200Response {
    /**
     * 
     * @type {FilesIntegrationGetRoomByShareToken200ResponseOcs}
     * @memberof FilesIntegrationGetRoomByShareToken200Response
     */
    ocs: FilesIntegrationGetRoomByShareToken200ResponseOcs;
}

/**
 * Check if a given object implements the FilesIntegrationGetRoomByShareToken200Response interface.
 */
export function instanceOfFilesIntegrationGetRoomByShareToken200Response(value: object): value is FilesIntegrationGetRoomByShareToken200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function FilesIntegrationGetRoomByShareToken200ResponseFromJSON(json: any): FilesIntegrationGetRoomByShareToken200Response {
    return FilesIntegrationGetRoomByShareToken200ResponseFromJSONTyped(json, false);
}

export function FilesIntegrationGetRoomByShareToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilesIntegrationGetRoomByShareToken200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': FilesIntegrationGetRoomByShareToken200ResponseOcsFromJSON(json['ocs']),
    };
}

export function FilesIntegrationGetRoomByShareToken200ResponseToJSON(value?: FilesIntegrationGetRoomByShareToken200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': FilesIntegrationGetRoomByShareToken200ResponseOcsToJSON(value['ocs']),
    };
}

