/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { MatterbridgeGetBridgeOfRoom200ResponseOcs } from './MatterbridgeGetBridgeOfRoom200ResponseOcs.ts';
import {
    MatterbridgeGetBridgeOfRoom200ResponseOcsFromJSON,
    MatterbridgeGetBridgeOfRoom200ResponseOcsFromJSONTyped,
    MatterbridgeGetBridgeOfRoom200ResponseOcsToJSON,
} from './MatterbridgeGetBridgeOfRoom200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface MatterbridgeGetBridgeOfRoom200Response
 */
export interface MatterbridgeGetBridgeOfRoom200Response {
    /**
     * 
     * @type {MatterbridgeGetBridgeOfRoom200ResponseOcs}
     * @memberof MatterbridgeGetBridgeOfRoom200Response
     */
    ocs: MatterbridgeGetBridgeOfRoom200ResponseOcs;
}

/**
 * Check if a given object implements the MatterbridgeGetBridgeOfRoom200Response interface.
 */
export function instanceOfMatterbridgeGetBridgeOfRoom200Response(value: object): value is MatterbridgeGetBridgeOfRoom200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function MatterbridgeGetBridgeOfRoom200ResponseFromJSON(json: any): MatterbridgeGetBridgeOfRoom200Response {
    return MatterbridgeGetBridgeOfRoom200ResponseFromJSONTyped(json, false);
}

export function MatterbridgeGetBridgeOfRoom200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatterbridgeGetBridgeOfRoom200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': MatterbridgeGetBridgeOfRoom200ResponseOcsFromJSON(json['ocs']),
    };
}

export function MatterbridgeGetBridgeOfRoom200ResponseToJSON(value?: MatterbridgeGetBridgeOfRoom200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': MatterbridgeGetBridgeOfRoom200ResponseOcsToJSON(value['ocs']),
    };
}

