/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface PollVote
 */
export interface PollVote {
    /**
     * 
     * @type {string}
     * @memberof PollVote
     */
    actorDisplayName: string;
    /**
     * 
     * @type {string}
     * @memberof PollVote
     */
    actorId: string;
    /**
     * 
     * @type {string}
     * @memberof PollVote
     */
    actorType: string;
    /**
     * 
     * @type {number}
     * @memberof PollVote
     */
    optionId: number;
}

/**
 * Check if a given object implements the PollVote interface.
 */
export function instanceOfPollVote(value: object): value is PollVote {
    if (!('actorDisplayName' in value) || value['actorDisplayName'] === undefined) return false;
    if (!('actorId' in value) || value['actorId'] === undefined) return false;
    if (!('actorType' in value) || value['actorType'] === undefined) return false;
    if (!('optionId' in value) || value['optionId'] === undefined) return false;
    return true;
}

export function PollVoteFromJSON(json: any): PollVote {
    return PollVoteFromJSONTyped(json, false);
}

export function PollVoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): PollVote {
    if (json == null) {
        return json;
    }
    return {
        
        'actorDisplayName': json['actorDisplayName'],
        'actorId': json['actorId'],
        'actorType': json['actorType'],
        'optionId': json['optionId'],
    };
}

export function PollVoteToJSON(value?: PollVote | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'actorDisplayName': value['actorDisplayName'],
        'actorId': value['actorId'],
        'actorType': value['actorType'],
        'optionId': value['optionId'],
    };
}

