/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface Reaction
 */
export interface Reaction {
    /**
     * 
     * @type {string}
     * @memberof Reaction
     */
    actorDisplayName: string;
    /**
     * 
     * @type {string}
     * @memberof Reaction
     */
    actorId: string;
    /**
     * 
     * @type {string}
     * @memberof Reaction
     */
    actorType: string;
    /**
     * 
     * @type {number}
     * @memberof Reaction
     */
    timestamp: number;
}

/**
 * Check if a given object implements the Reaction interface.
 */
export function instanceOfReaction(value: object): value is Reaction {
    if (!('actorDisplayName' in value) || value['actorDisplayName'] === undefined) return false;
    if (!('actorId' in value) || value['actorId'] === undefined) return false;
    if (!('actorType' in value) || value['actorType'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ReactionFromJSON(json: any): Reaction {
    return ReactionFromJSONTyped(json, false);
}

export function ReactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reaction {
    if (json == null) {
        return json;
    }
    return {
        
        'actorDisplayName': json['actorDisplayName'],
        'actorId': json['actorId'],
        'actorType': json['actorType'],
        'timestamp': json['timestamp'],
    };
}

export function ReactionToJSON(value?: Reaction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'actorDisplayName': value['actorDisplayName'],
        'actorId': value['actorId'],
        'actorType': value['actorType'],
        'timestamp': value['timestamp'],
    };
}

