/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { ReactionGetReactions200ResponseOcs } from './ReactionGetReactions200ResponseOcs.ts';
import {
    ReactionGetReactions200ResponseOcsFromJSON,
    ReactionGetReactions200ResponseOcsFromJSONTyped,
    ReactionGetReactions200ResponseOcsToJSON,
} from './ReactionGetReactions200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface ReactionGetReactions200Response
 */
export interface ReactionGetReactions200Response {
    /**
     * 
     * @type {ReactionGetReactions200ResponseOcs}
     * @memberof ReactionGetReactions200Response
     */
    ocs: ReactionGetReactions200ResponseOcs;
}

/**
 * Check if a given object implements the ReactionGetReactions200Response interface.
 */
export function instanceOfReactionGetReactions200Response(value: object): value is ReactionGetReactions200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function ReactionGetReactions200ResponseFromJSON(json: any): ReactionGetReactions200Response {
    return ReactionGetReactions200ResponseFromJSONTyped(json, false);
}

export function ReactionGetReactions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReactionGetReactions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': ReactionGetReactions200ResponseOcsFromJSON(json['ocs']),
    };
}

export function ReactionGetReactions200ResponseToJSON(value?: ReactionGetReactions200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': ReactionGetReactions200ResponseOcsToJSON(value['ocs']),
    };
}

