/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { RoomGetCapabilities200ResponseOcs } from './RoomGetCapabilities200ResponseOcs.ts';
import {
    RoomGetCapabilities200ResponseOcsFromJSON,
    RoomGetCapabilities200ResponseOcsFromJSONTyped,
    RoomGetCapabilities200ResponseOcsToJSON,
} from './RoomGetCapabilities200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface RoomGetCapabilities200Response
 */
export interface RoomGetCapabilities200Response {
    /**
     * 
     * @type {RoomGetCapabilities200ResponseOcs}
     * @memberof RoomGetCapabilities200Response
     */
    ocs: RoomGetCapabilities200ResponseOcs;
}

/**
 * Check if a given object implements the RoomGetCapabilities200Response interface.
 */
export function instanceOfRoomGetCapabilities200Response(value: object): value is RoomGetCapabilities200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function RoomGetCapabilities200ResponseFromJSON(json: any): RoomGetCapabilities200Response {
    return RoomGetCapabilities200ResponseFromJSONTyped(json, false);
}

export function RoomGetCapabilities200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomGetCapabilities200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': RoomGetCapabilities200ResponseOcsFromJSON(json['ocs']),
    };
}

export function RoomGetCapabilities200ResponseToJSON(value?: RoomGetCapabilities200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': RoomGetCapabilities200ResponseOcsToJSON(value['ocs']),
    };
}

