/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { RoomJoinRoom403ResponseOcs } from './RoomJoinRoom403ResponseOcs.ts';
import {
    RoomJoinRoom403ResponseOcsFromJSON,
    RoomJoinRoom403ResponseOcsFromJSONTyped,
    RoomJoinRoom403ResponseOcsToJSON,
} from './RoomJoinRoom403ResponseOcs.ts';

/**
 * 
 * @export
 * @interface RoomJoinRoom403Response
 */
export interface RoomJoinRoom403Response {
    /**
     * 
     * @type {RoomJoinRoom403ResponseOcs}
     * @memberof RoomJoinRoom403Response
     */
    ocs: RoomJoinRoom403ResponseOcs;
}

/**
 * Check if a given object implements the RoomJoinRoom403Response interface.
 */
export function instanceOfRoomJoinRoom403Response(value: object): value is RoomJoinRoom403Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function RoomJoinRoom403ResponseFromJSON(json: any): RoomJoinRoom403Response {
    return RoomJoinRoom403ResponseFromJSONTyped(json, false);
}

export function RoomJoinRoom403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomJoinRoom403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': RoomJoinRoom403ResponseOcsFromJSON(json['ocs']),
    };
}

export function RoomJoinRoom403ResponseToJSON(value?: RoomJoinRoom403Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': RoomJoinRoom403ResponseOcsToJSON(value['ocs']),
    };
}

