/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { OCSMeta } from './OCSMeta.ts';
import {
    OCSMetaFromJSON,
    OCSMetaFromJSONTyped,
    OCSMetaToJSON,
} from './OCSMeta.ts';

/**
 * 
 * @export
 * @interface SignalingPullMessages400ResponseOcs
 */
export interface SignalingPullMessages400ResponseOcs {
    /**
     * 
     * @type {OCSMeta}
     * @memberof SignalingPullMessages400ResponseOcs
     */
    meta: OCSMeta;
    /**
     * 
     * @type {string}
     * @memberof SignalingPullMessages400ResponseOcs
     */
    data: string;
}

/**
 * Check if a given object implements the SignalingPullMessages400ResponseOcs interface.
 */
export function instanceOfSignalingPullMessages400ResponseOcs(value: object): value is SignalingPullMessages400ResponseOcs {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SignalingPullMessages400ResponseOcsFromJSON(json: any): SignalingPullMessages400ResponseOcs {
    return SignalingPullMessages400ResponseOcsFromJSONTyped(json, false);
}

export function SignalingPullMessages400ResponseOcsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalingPullMessages400ResponseOcs {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': OCSMetaFromJSON(json['meta']),
        'data': json['data'],
    };
}

export function SignalingPullMessages400ResponseOcsToJSON(value?: SignalingPullMessages400ResponseOcs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'meta': OCSMetaToJSON(value['meta']),
        'data': value['data'],
    };
}

