/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { SignalingGetSettings200ResponseOcs } from './SignalingGetSettings200ResponseOcs.ts';
import {
    SignalingGetSettings200ResponseOcsFromJSON,
    SignalingGetSettings200ResponseOcsFromJSONTyped,
    SignalingGetSettings200ResponseOcsToJSON,
} from './SignalingGetSettings200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface SignalingGetSettings200Response
 */
export interface SignalingGetSettings200Response {
    /**
     * 
     * @type {SignalingGetSettings200ResponseOcs}
     * @memberof SignalingGetSettings200Response
     */
    ocs: SignalingGetSettings200ResponseOcs;
}

/**
 * Check if a given object implements the SignalingGetSettings200Response interface.
 */
export function instanceOfSignalingGetSettings200Response(value: object): value is SignalingGetSettings200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function SignalingGetSettings200ResponseFromJSON(json: any): SignalingGetSettings200Response {
    return SignalingGetSettings200ResponseFromJSONTyped(json, false);
}

export function SignalingGetSettings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalingGetSettings200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': SignalingGetSettings200ResponseOcsFromJSON(json['ocs']),
    };
}

export function SignalingGetSettings200ResponseToJSON(value?: SignalingGetSettings200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': SignalingGetSettings200ResponseOcsToJSON(value['ocs']),
    };
}

