/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface SignalingSettingsHelloAuthParams10
 */
export interface SignalingSettingsHelloAuthParams10 {
    /**
     * 
     * @type {string}
     * @memberof SignalingSettingsHelloAuthParams10
     */
    userid: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignalingSettingsHelloAuthParams10
     */
    ticket: string;
}

/**
 * Check if a given object implements the SignalingSettingsHelloAuthParams10 interface.
 */
export function instanceOfSignalingSettingsHelloAuthParams10(value: object): value is SignalingSettingsHelloAuthParams10 {
    if (!('userid' in value) || value['userid'] === undefined) return false;
    if (!('ticket' in value) || value['ticket'] === undefined) return false;
    return true;
}

export function SignalingSettingsHelloAuthParams10FromJSON(json: any): SignalingSettingsHelloAuthParams10 {
    return SignalingSettingsHelloAuthParams10FromJSONTyped(json, false);
}

export function SignalingSettingsHelloAuthParams10FromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalingSettingsHelloAuthParams10 {
    if (json == null) {
        return json;
    }
    return {
        
        'userid': json['userid'],
        'ticket': json['ticket'],
    };
}

export function SignalingSettingsHelloAuthParams10ToJSON(value?: SignalingSettingsHelloAuthParams10 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userid': value['userid'],
        'ticket': value['ticket'],
    };
}

