/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.ts';
import type {
  AutoCompleteGet200Response,
  AutoCompleteGetRequest,
} from '../models/index.ts';
import {
    AutoCompleteGet200ResponseFromJSON,
    AutoCompleteGet200ResponseToJSON,
    AutoCompleteGetRequestFromJSON,
    AutoCompleteGetRequestToJSON,
} from '../models/index.ts';

export interface AutoCompleteGetOperationRequest {
    oCSAPIRequest: boolean;
    autoCompleteGetRequest: AutoCompleteGetRequest;
}

/**
 * 
 */
export class AutoCompleteApi extends runtime.BaseAPI {

    /**
     * Autocomplete a query
     */
    async autoCompleteGetRaw(requestParameters: AutoCompleteGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AutoCompleteGet200Response>> {
        if (requestParameters['oCSAPIRequest'] == null) {
            throw new runtime.RequiredError(
                'oCSAPIRequest',
                'Required parameter "oCSAPIRequest" was null or undefined when calling autoCompleteGet().'
            );
        }

        if (requestParameters['autoCompleteGetRequest'] == null) {
            throw new runtime.RequiredError(
                'autoCompleteGetRequest',
                'Required parameter "autoCompleteGetRequest" was null or undefined when calling autoCompleteGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['oCSAPIRequest'] != null) {
            headerParameters['OCS-APIRequest'] = String(requestParameters['oCSAPIRequest']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ocs/v2.php/core/autocomplete/get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: AutoCompleteGetRequestToJSON(requestParameters['autoCompleteGetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AutoCompleteGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Autocomplete a query
     */
    async autoCompleteGet(requestParameters: AutoCompleteGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AutoCompleteGet200Response> {
        const response = await this.autoCompleteGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
