/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.ts';
import type {
  PreviewGetPreviewByFileIdRequest,
  PreviewGetPreviewRequest,
} from '../models/index.ts';
import {
    PreviewGetPreviewByFileIdRequestFromJSON,
    PreviewGetPreviewByFileIdRequestToJSON,
    PreviewGetPreviewRequestFromJSON,
    PreviewGetPreviewRequestToJSON,
} from '../models/index.ts';

export interface PreviewGetPreviewOperationRequest {
    previewGetPreviewRequest?: PreviewGetPreviewRequest;
}

export interface PreviewGetPreviewByFileIdOperationRequest {
    previewGetPreviewByFileIdRequest?: PreviewGetPreviewByFileIdRequest;
}

/**
 * 
 */
export class PreviewApi extends runtime.BaseAPI {

    /**
     * Get a preview by file path
     */
    async previewGetPreviewRaw(requestParameters: PreviewGetPreviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/index.php/core/preview.png`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: PreviewGetPreviewRequestToJSON(requestParameters['previewGetPreviewRequest']),
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Get a preview by file path
     */
    async previewGetPreview(requestParameters: PreviewGetPreviewOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.previewGetPreviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a preview by file ID
     */
    async previewGetPreviewByFileIdRaw(requestParameters: PreviewGetPreviewByFileIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/index.php/core/preview`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: PreviewGetPreviewByFileIdRequestToJSON(requestParameters['previewGetPreviewByFileIdRequest']),
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Get a preview by file ID
     */
    async previewGetPreviewByFileId(requestParameters: PreviewGetPreviewByFileIdOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.previewGetPreviewByFileIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
