/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.ts';
import type {
  AppPasswordGetAppPassword403Response,
  WhatsNewDismissRequest,
  WhatsNewGet200Response,
} from '../models/index.ts';
import {
    AppPasswordGetAppPassword403ResponseFromJSON,
    AppPasswordGetAppPassword403ResponseToJSON,
    WhatsNewDismissRequestFromJSON,
    WhatsNewDismissRequestToJSON,
    WhatsNewGet200ResponseFromJSON,
    WhatsNewGet200ResponseToJSON,
} from '../models/index.ts';

export interface WhatsNewDismissOperationRequest {
    oCSAPIRequest: boolean;
    whatsNewDismissRequest: WhatsNewDismissRequest;
}

export interface WhatsNewGetRequest {
    oCSAPIRequest: boolean;
}

/**
 * 
 */
export class WhatsNewApi extends runtime.BaseAPI {

    /**
     * Dismiss the changes
     */
    async whatsNewDismissRaw(requestParameters: WhatsNewDismissOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppPasswordGetAppPassword403Response>> {
        if (requestParameters['oCSAPIRequest'] == null) {
            throw new runtime.RequiredError(
                'oCSAPIRequest',
                'Required parameter "oCSAPIRequest" was null or undefined when calling whatsNewDismiss().'
            );
        }

        if (requestParameters['whatsNewDismissRequest'] == null) {
            throw new runtime.RequiredError(
                'whatsNewDismissRequest',
                'Required parameter "whatsNewDismissRequest" was null or undefined when calling whatsNewDismiss().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['oCSAPIRequest'] != null) {
            headerParameters['OCS-APIRequest'] = String(requestParameters['oCSAPIRequest']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ocs/v2.php/core/whatsnew`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WhatsNewDismissRequestToJSON(requestParameters['whatsNewDismissRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppPasswordGetAppPassword403ResponseFromJSON(jsonValue));
    }

    /**
     * Dismiss the changes
     */
    async whatsNewDismiss(requestParameters: WhatsNewDismissOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppPasswordGetAppPassword403Response> {
        const response = await this.whatsNewDismissRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the changes
     */
    async whatsNewGetRaw(requestParameters: WhatsNewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WhatsNewGet200Response>> {
        if (requestParameters['oCSAPIRequest'] == null) {
            throw new runtime.RequiredError(
                'oCSAPIRequest',
                'Required parameter "oCSAPIRequest" was null or undefined when calling whatsNewGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['oCSAPIRequest'] != null) {
            headerParameters['OCS-APIRequest'] = String(requestParameters['oCSAPIRequest']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ocs/v2.php/core/whatsnew`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WhatsNewGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get the changes
     */
    async whatsNewGet(requestParameters: WhatsNewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WhatsNewGet200Response | null | undefined > {
        const response = await this.whatsNewGetRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
