/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { AppPasswordGetAppPassword200ResponseOcs } from './AppPasswordGetAppPassword200ResponseOcs.ts';
import {
    AppPasswordGetAppPassword200ResponseOcsFromJSON,
    AppPasswordGetAppPassword200ResponseOcsFromJSONTyped,
    AppPasswordGetAppPassword200ResponseOcsToJSON,
} from './AppPasswordGetAppPassword200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface AppPasswordGetAppPassword200Response
 */
export interface AppPasswordGetAppPassword200Response {
    /**
     * 
     * @type {AppPasswordGetAppPassword200ResponseOcs}
     * @memberof AppPasswordGetAppPassword200Response
     */
    ocs: AppPasswordGetAppPassword200ResponseOcs;
}

/**
 * Check if a given object implements the AppPasswordGetAppPassword200Response interface.
 */
export function instanceOfAppPasswordGetAppPassword200Response(value: object): value is AppPasswordGetAppPassword200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function AppPasswordGetAppPassword200ResponseFromJSON(json: any): AppPasswordGetAppPassword200Response {
    return AppPasswordGetAppPassword200ResponseFromJSONTyped(json, false);
}

export function AppPasswordGetAppPassword200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPasswordGetAppPassword200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': AppPasswordGetAppPassword200ResponseOcsFromJSON(json['ocs']),
    };
}

export function AppPasswordGetAppPassword200ResponseToJSON(value?: AppPasswordGetAppPassword200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': AppPasswordGetAppPassword200ResponseOcsToJSON(value['ocs']),
    };
}

