/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { HoverCardGetUser200ResponseOcs } from './HoverCardGetUser200ResponseOcs.ts';
import {
    HoverCardGetUser200ResponseOcsFromJSON,
    HoverCardGetUser200ResponseOcsFromJSONTyped,
    HoverCardGetUser200ResponseOcsToJSON,
} from './HoverCardGetUser200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface HoverCardGetUser200Response
 */
export interface HoverCardGetUser200Response {
    /**
     * 
     * @type {HoverCardGetUser200ResponseOcs}
     * @memberof HoverCardGetUser200Response
     */
    ocs: HoverCardGetUser200ResponseOcs;
}

/**
 * Check if a given object implements the HoverCardGetUser200Response interface.
 */
export function instanceOfHoverCardGetUser200Response(value: object): value is HoverCardGetUser200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function HoverCardGetUser200ResponseFromJSON(json: any): HoverCardGetUser200Response {
    return HoverCardGetUser200ResponseFromJSONTyped(json, false);
}

export function HoverCardGetUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HoverCardGetUser200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': HoverCardGetUser200ResponseOcsFromJSON(json['ocs']),
    };
}

export function HoverCardGetUser200ResponseToJSON(value?: HoverCardGetUser200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': HoverCardGetUser200ResponseOcsToJSON(value['ocs']),
    };
}

