/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { LoginFlowV2Poll } from './LoginFlowV2Poll.ts';
import {
    LoginFlowV2PollFromJSON,
    LoginFlowV2PollFromJSONTyped,
    LoginFlowV2PollToJSON,
} from './LoginFlowV2Poll.ts';

/**
 * 
 * @export
 * @interface LoginFlowV2
 */
export interface LoginFlowV2 {
    /**
     * 
     * @type {LoginFlowV2Poll}
     * @memberof LoginFlowV2
     */
    poll: LoginFlowV2Poll;
    /**
     * 
     * @type {string}
     * @memberof LoginFlowV2
     */
    login: string;
}

/**
 * Check if a given object implements the LoginFlowV2 interface.
 */
export function instanceOfLoginFlowV2(value: object): value is LoginFlowV2 {
    if (!('poll' in value) || value['poll'] === undefined) return false;
    if (!('login' in value) || value['login'] === undefined) return false;
    return true;
}

export function LoginFlowV2FromJSON(json: any): LoginFlowV2 {
    return LoginFlowV2FromJSONTyped(json, false);
}

export function LoginFlowV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginFlowV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'poll': LoginFlowV2PollFromJSON(json['poll']),
        'login': json['login'],
    };
}

export function LoginFlowV2ToJSON(value?: LoginFlowV2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'poll': LoginFlowV2PollToJSON(value['poll']),
        'login': value['login'],
    };
}

