/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { ReferenceApiTouchProvider200ResponseOcs } from './ReferenceApiTouchProvider200ResponseOcs.ts';
import {
    ReferenceApiTouchProvider200ResponseOcsFromJSON,
    ReferenceApiTouchProvider200ResponseOcsFromJSONTyped,
    ReferenceApiTouchProvider200ResponseOcsToJSON,
} from './ReferenceApiTouchProvider200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface ReferenceApiTouchProvider200Response
 */
export interface ReferenceApiTouchProvider200Response {
    /**
     * 
     * @type {ReferenceApiTouchProvider200ResponseOcs}
     * @memberof ReferenceApiTouchProvider200Response
     */
    ocs: ReferenceApiTouchProvider200ResponseOcs;
}

/**
 * Check if a given object implements the ReferenceApiTouchProvider200Response interface.
 */
export function instanceOfReferenceApiTouchProvider200Response(value: object): value is ReferenceApiTouchProvider200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function ReferenceApiTouchProvider200ResponseFromJSON(json: any): ReferenceApiTouchProvider200Response {
    return ReferenceApiTouchProvider200ResponseFromJSONTyped(json, false);
}

export function ReferenceApiTouchProvider200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceApiTouchProvider200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': ReferenceApiTouchProvider200ResponseOcsFromJSON(json['ocs']),
    };
}

export function ReferenceApiTouchProvider200ResponseToJSON(value?: ReferenceApiTouchProvider200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': ReferenceApiTouchProvider200ResponseOcsToJSON(value['ocs']),
    };
}

