/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { TaskProcessingApiGetNextScheduledTask200ResponseOcs } from './TaskProcessingApiGetNextScheduledTask200ResponseOcs.ts';
import {
    TaskProcessingApiGetNextScheduledTask200ResponseOcsFromJSON,
    TaskProcessingApiGetNextScheduledTask200ResponseOcsFromJSONTyped,
    TaskProcessingApiGetNextScheduledTask200ResponseOcsToJSON,
} from './TaskProcessingApiGetNextScheduledTask200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface TaskProcessingApiGetNextScheduledTask200Response
 */
export interface TaskProcessingApiGetNextScheduledTask200Response {
    /**
     * 
     * @type {TaskProcessingApiGetNextScheduledTask200ResponseOcs}
     * @memberof TaskProcessingApiGetNextScheduledTask200Response
     */
    ocs: TaskProcessingApiGetNextScheduledTask200ResponseOcs;
}

/**
 * Check if a given object implements the TaskProcessingApiGetNextScheduledTask200Response interface.
 */
export function instanceOfTaskProcessingApiGetNextScheduledTask200Response(value: object): value is TaskProcessingApiGetNextScheduledTask200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function TaskProcessingApiGetNextScheduledTask200ResponseFromJSON(json: any): TaskProcessingApiGetNextScheduledTask200Response {
    return TaskProcessingApiGetNextScheduledTask200ResponseFromJSONTyped(json, false);
}

export function TaskProcessingApiGetNextScheduledTask200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProcessingApiGetNextScheduledTask200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': TaskProcessingApiGetNextScheduledTask200ResponseOcsFromJSON(json['ocs']),
    };
}

export function TaskProcessingApiGetNextScheduledTask200ResponseToJSON(value?: TaskProcessingApiGetNextScheduledTask200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': TaskProcessingApiGetNextScheduledTask200ResponseOcsToJSON(value['ocs']),
    };
}

