/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { TaskProcessingTask } from './TaskProcessingTask.ts';
import {
    TaskProcessingTaskFromJSON,
    TaskProcessingTaskFromJSONTyped,
    TaskProcessingTaskToJSON,
} from './TaskProcessingTask.ts';

/**
 * 
 * @export
 * @interface TaskProcessingApiListTasksByApp200ResponseOcsData
 */
export interface TaskProcessingApiListTasksByApp200ResponseOcsData {
    /**
     * 
     * @type {Array<TaskProcessingTask>}
     * @memberof TaskProcessingApiListTasksByApp200ResponseOcsData
     */
    tasks: Array<TaskProcessingTask>;
}

/**
 * Check if a given object implements the TaskProcessingApiListTasksByApp200ResponseOcsData interface.
 */
export function instanceOfTaskProcessingApiListTasksByApp200ResponseOcsData(value: object): value is TaskProcessingApiListTasksByApp200ResponseOcsData {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    return true;
}

export function TaskProcessingApiListTasksByApp200ResponseOcsDataFromJSON(json: any): TaskProcessingApiListTasksByApp200ResponseOcsData {
    return TaskProcessingApiListTasksByApp200ResponseOcsDataFromJSONTyped(json, false);
}

export function TaskProcessingApiListTasksByApp200ResponseOcsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProcessingApiListTasksByApp200ResponseOcsData {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(TaskProcessingTaskFromJSON)),
    };
}

export function TaskProcessingApiListTasksByApp200ResponseOcsDataToJSON(value?: TaskProcessingApiListTasksByApp200ResponseOcsData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(TaskProcessingTaskToJSON)),
    };
}

