/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { TaskProcessingTaskTypeInputShapeDefaultsValue } from './TaskProcessingTaskTypeInputShapeDefaultsValue.ts';
import {
    TaskProcessingTaskTypeInputShapeDefaultsValueFromJSON,
    TaskProcessingTaskTypeInputShapeDefaultsValueFromJSONTyped,
    TaskProcessingTaskTypeInputShapeDefaultsValueToJSON,
} from './TaskProcessingTaskTypeInputShapeDefaultsValue.ts';
import type { TaskProcessingTaskTypeInputShapeEnumValuesInnerInner } from './TaskProcessingTaskTypeInputShapeEnumValuesInnerInner.ts';
import {
    TaskProcessingTaskTypeInputShapeEnumValuesInnerInnerFromJSON,
    TaskProcessingTaskTypeInputShapeEnumValuesInnerInnerFromJSONTyped,
    TaskProcessingTaskTypeInputShapeEnumValuesInnerInnerToJSON,
} from './TaskProcessingTaskTypeInputShapeEnumValuesInnerInner.ts';
import type { TaskProcessingShape } from './TaskProcessingShape.ts';
import {
    TaskProcessingShapeFromJSON,
    TaskProcessingShapeFromJSONTyped,
    TaskProcessingShapeToJSON,
} from './TaskProcessingShape.ts';

/**
 * 
 * @export
 * @interface TaskProcessingTaskType
 */
export interface TaskProcessingTaskType {
    /**
     * 
     * @type {string}
     * @memberof TaskProcessingTaskType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TaskProcessingTaskType
     */
    description: string;
    /**
     * 
     * @type {Array<TaskProcessingShape>}
     * @memberof TaskProcessingTaskType
     */
    inputShape: Array<TaskProcessingShape>;
    /**
     * 
     * @type {Array<Array<TaskProcessingTaskTypeInputShapeEnumValuesInnerInner>>}
     * @memberof TaskProcessingTaskType
     */
    inputShapeEnumValues: Array<Array<TaskProcessingTaskTypeInputShapeEnumValuesInnerInner>>;
    /**
     * 
     * @type {{ [key: string]: TaskProcessingTaskTypeInputShapeDefaultsValue; }}
     * @memberof TaskProcessingTaskType
     */
    inputShapeDefaults: { [key: string]: TaskProcessingTaskTypeInputShapeDefaultsValue; };
    /**
     * 
     * @type {Array<TaskProcessingShape>}
     * @memberof TaskProcessingTaskType
     */
    optionalInputShape: Array<TaskProcessingShape>;
    /**
     * 
     * @type {Array<Array<TaskProcessingTaskTypeInputShapeEnumValuesInnerInner>>}
     * @memberof TaskProcessingTaskType
     */
    optionalInputShapeEnumValues: Array<Array<TaskProcessingTaskTypeInputShapeEnumValuesInnerInner>>;
    /**
     * 
     * @type {{ [key: string]: TaskProcessingTaskTypeInputShapeDefaultsValue; }}
     * @memberof TaskProcessingTaskType
     */
    optionalInputShapeDefaults: { [key: string]: TaskProcessingTaskTypeInputShapeDefaultsValue; };
    /**
     * 
     * @type {Array<TaskProcessingShape>}
     * @memberof TaskProcessingTaskType
     */
    outputShape: Array<TaskProcessingShape>;
    /**
     * 
     * @type {Array<Array<TaskProcessingTaskTypeInputShapeEnumValuesInnerInner>>}
     * @memberof TaskProcessingTaskType
     */
    outputShapeEnumValues: Array<Array<TaskProcessingTaskTypeInputShapeEnumValuesInnerInner>>;
    /**
     * 
     * @type {Array<TaskProcessingShape>}
     * @memberof TaskProcessingTaskType
     */
    optionalOutputShape: Array<TaskProcessingShape>;
    /**
     * 
     * @type {Array<Array<TaskProcessingTaskTypeInputShapeEnumValuesInnerInner>>}
     * @memberof TaskProcessingTaskType
     */
    optionalOutputShapeEnumValues: Array<Array<TaskProcessingTaskTypeInputShapeEnumValuesInnerInner>>;
}

/**
 * Check if a given object implements the TaskProcessingTaskType interface.
 */
export function instanceOfTaskProcessingTaskType(value: object): value is TaskProcessingTaskType {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('inputShape' in value) || value['inputShape'] === undefined) return false;
    if (!('inputShapeEnumValues' in value) || value['inputShapeEnumValues'] === undefined) return false;
    if (!('inputShapeDefaults' in value) || value['inputShapeDefaults'] === undefined) return false;
    if (!('optionalInputShape' in value) || value['optionalInputShape'] === undefined) return false;
    if (!('optionalInputShapeEnumValues' in value) || value['optionalInputShapeEnumValues'] === undefined) return false;
    if (!('optionalInputShapeDefaults' in value) || value['optionalInputShapeDefaults'] === undefined) return false;
    if (!('outputShape' in value) || value['outputShape'] === undefined) return false;
    if (!('outputShapeEnumValues' in value) || value['outputShapeEnumValues'] === undefined) return false;
    if (!('optionalOutputShape' in value) || value['optionalOutputShape'] === undefined) return false;
    if (!('optionalOutputShapeEnumValues' in value) || value['optionalOutputShapeEnumValues'] === undefined) return false;
    return true;
}

export function TaskProcessingTaskTypeFromJSON(json: any): TaskProcessingTaskType {
    return TaskProcessingTaskTypeFromJSONTyped(json, false);
}

export function TaskProcessingTaskTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProcessingTaskType {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'inputShape': ((json['inputShape'] as Array<any>).map(TaskProcessingShapeFromJSON)),
        'inputShapeEnumValues': json['inputShapeEnumValues'],
        'inputShapeDefaults': (mapValues(json['inputShapeDefaults'], TaskProcessingTaskTypeInputShapeDefaultsValueFromJSON)),
        'optionalInputShape': ((json['optionalInputShape'] as Array<any>).map(TaskProcessingShapeFromJSON)),
        'optionalInputShapeEnumValues': json['optionalInputShapeEnumValues'],
        'optionalInputShapeDefaults': (mapValues(json['optionalInputShapeDefaults'], TaskProcessingTaskTypeInputShapeDefaultsValueFromJSON)),
        'outputShape': ((json['outputShape'] as Array<any>).map(TaskProcessingShapeFromJSON)),
        'outputShapeEnumValues': json['outputShapeEnumValues'],
        'optionalOutputShape': ((json['optionalOutputShape'] as Array<any>).map(TaskProcessingShapeFromJSON)),
        'optionalOutputShapeEnumValues': json['optionalOutputShapeEnumValues'],
    };
}

export function TaskProcessingTaskTypeToJSON(value?: TaskProcessingTaskType | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'inputShape': ((value['inputShape'] as Array<any>).map(TaskProcessingShapeToJSON)),
        'inputShapeEnumValues': value['inputShapeEnumValues'],
        'inputShapeDefaults': (mapValues(value['inputShapeDefaults'], TaskProcessingTaskTypeInputShapeDefaultsValueToJSON)),
        'optionalInputShape': ((value['optionalInputShape'] as Array<any>).map(TaskProcessingShapeToJSON)),
        'optionalInputShapeEnumValues': value['optionalInputShapeEnumValues'],
        'optionalInputShapeDefaults': (mapValues(value['optionalInputShapeDefaults'], TaskProcessingTaskTypeInputShapeDefaultsValueToJSON)),
        'outputShape': ((value['outputShape'] as Array<any>).map(TaskProcessingShapeToJSON)),
        'outputShapeEnumValues': value['outputShapeEnumValues'],
        'optionalOutputShape': ((value['optionalOutputShape'] as Array<any>).map(TaskProcessingShapeToJSON)),
        'optionalOutputShapeEnumValues': value['optionalOutputShapeEnumValues'],
    };
}

