/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface TaskProcessingTaskTypeInputShapeEnumValuesInnerInner
 */
export interface TaskProcessingTaskTypeInputShapeEnumValuesInnerInner {
    /**
     * 
     * @type {string}
     * @memberof TaskProcessingTaskTypeInputShapeEnumValuesInnerInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TaskProcessingTaskTypeInputShapeEnumValuesInnerInner
     */
    value: string;
}

/**
 * Check if a given object implements the TaskProcessingTaskTypeInputShapeEnumValuesInnerInner interface.
 */
export function instanceOfTaskProcessingTaskTypeInputShapeEnumValuesInnerInner(value: object): value is TaskProcessingTaskTypeInputShapeEnumValuesInnerInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function TaskProcessingTaskTypeInputShapeEnumValuesInnerInnerFromJSON(json: any): TaskProcessingTaskTypeInputShapeEnumValuesInnerInner {
    return TaskProcessingTaskTypeInputShapeEnumValuesInnerInnerFromJSONTyped(json, false);
}

export function TaskProcessingTaskTypeInputShapeEnumValuesInnerInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProcessingTaskTypeInputShapeEnumValuesInnerInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function TaskProcessingTaskTypeInputShapeEnumValuesInnerInnerToJSON(value?: TaskProcessingTaskTypeInputShapeEnumValuesInnerInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

