/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { Team } from './Team.ts';
import {
    TeamFromJSON,
    TeamFromJSONTyped,
    TeamToJSON,
} from './Team.ts';

/**
 * 
 * @export
 * @interface TeamsApiListTeams200ResponseOcsData
 */
export interface TeamsApiListTeams200ResponseOcsData {
    /**
     * 
     * @type {Array<Team>}
     * @memberof TeamsApiListTeams200ResponseOcsData
     */
    teams: Array<Team>;
}

/**
 * Check if a given object implements the TeamsApiListTeams200ResponseOcsData interface.
 */
export function instanceOfTeamsApiListTeams200ResponseOcsData(value: object): value is TeamsApiListTeams200ResponseOcsData {
    if (!('teams' in value) || value['teams'] === undefined) return false;
    return true;
}

export function TeamsApiListTeams200ResponseOcsDataFromJSON(json: any): TeamsApiListTeams200ResponseOcsData {
    return TeamsApiListTeams200ResponseOcsDataFromJSONTyped(json, false);
}

export function TeamsApiListTeams200ResponseOcsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamsApiListTeams200ResponseOcsData {
    if (json == null) {
        return json;
    }
    return {
        
        'teams': ((json['teams'] as Array<any>).map(TeamFromJSON)),
    };
}

export function TeamsApiListTeams200ResponseOcsDataToJSON(value?: TeamsApiListTeams200ResponseOcsData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'teams': ((value['teams'] as Array<any>).map(TeamToJSON)),
    };
}

