/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface TeamResource
 */
export interface TeamResource {
    /**
     * 
     * @type {number}
     * @memberof TeamResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TeamResource
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof TeamResource
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof TeamResource
     */
    iconSvg: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamResource
     */
    iconURL: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamResource
     */
    iconEmoji: string | null;
}

/**
 * Check if a given object implements the TeamResource interface.
 */
export function instanceOfTeamResource(value: object): value is TeamResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('iconSvg' in value) || value['iconSvg'] === undefined) return false;
    if (!('iconURL' in value) || value['iconURL'] === undefined) return false;
    if (!('iconEmoji' in value) || value['iconEmoji'] === undefined) return false;
    return true;
}

export function TeamResourceFromJSON(json: any): TeamResource {
    return TeamResourceFromJSONTyped(json, false);
}

export function TeamResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'url': json['url'],
        'iconSvg': json['iconSvg'],
        'iconURL': json['iconURL'],
        'iconEmoji': json['iconEmoji'],
    };
}

export function TeamResourceToJSON(value?: TeamResource | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'label': value['label'],
        'url': value['url'],
        'iconSvg': value['iconSvg'],
        'iconURL': value['iconURL'],
        'iconEmoji': value['iconEmoji'],
    };
}

