/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { OCSMeta } from './OCSMeta.ts';
import {
    OCSMetaFromJSON,
    OCSMetaFromJSONTyped,
    OCSMetaToJSON,
} from './OCSMeta.ts';
import type { TextToImageApiSchedule200ResponseOcsData } from './TextToImageApiSchedule200ResponseOcsData.ts';
import {
    TextToImageApiSchedule200ResponseOcsDataFromJSON,
    TextToImageApiSchedule200ResponseOcsDataFromJSONTyped,
    TextToImageApiSchedule200ResponseOcsDataToJSON,
} from './TextToImageApiSchedule200ResponseOcsData.ts';

/**
 * 
 * @export
 * @interface TextToImageApiSchedule200ResponseOcs
 */
export interface TextToImageApiSchedule200ResponseOcs {
    /**
     * 
     * @type {OCSMeta}
     * @memberof TextToImageApiSchedule200ResponseOcs
     */
    meta: OCSMeta;
    /**
     * 
     * @type {TextToImageApiSchedule200ResponseOcsData}
     * @memberof TextToImageApiSchedule200ResponseOcs
     */
    data: TextToImageApiSchedule200ResponseOcsData;
}

/**
 * Check if a given object implements the TextToImageApiSchedule200ResponseOcs interface.
 */
export function instanceOfTextToImageApiSchedule200ResponseOcs(value: object): value is TextToImageApiSchedule200ResponseOcs {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TextToImageApiSchedule200ResponseOcsFromJSON(json: any): TextToImageApiSchedule200ResponseOcs {
    return TextToImageApiSchedule200ResponseOcsFromJSONTyped(json, false);
}

export function TextToImageApiSchedule200ResponseOcsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextToImageApiSchedule200ResponseOcs {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': OCSMetaFromJSON(json['meta']),
        'data': TextToImageApiSchedule200ResponseOcsDataFromJSON(json['data']),
    };
}

export function TextToImageApiSchedule200ResponseOcsToJSON(value?: TextToImageApiSchedule200ResponseOcs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'meta': OCSMetaToJSON(value['meta']),
        'data': TextToImageApiSchedule200ResponseOcsDataToJSON(value['data']),
    };
}

