/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface TranslationApiTranslateRequest
 */
export interface TranslationApiTranslateRequest {
    /**
     * Text to be translated
     * @type {string}
     * @memberof TranslationApiTranslateRequest
     */
    text: string;
    /**
     * Language to translate from
     * @type {string}
     * @memberof TranslationApiTranslateRequest
     */
    fromLanguage?: string;
    /**
     * Language to translate to
     * @type {string}
     * @memberof TranslationApiTranslateRequest
     */
    toLanguage: string;
}

/**
 * Check if a given object implements the TranslationApiTranslateRequest interface.
 */
export function instanceOfTranslationApiTranslateRequest(value: object): value is TranslationApiTranslateRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('toLanguage' in value) || value['toLanguage'] === undefined) return false;
    return true;
}

export function TranslationApiTranslateRequestFromJSON(json: any): TranslationApiTranslateRequest {
    return TranslationApiTranslateRequestFromJSONTyped(json, false);
}

export function TranslationApiTranslateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslationApiTranslateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'fromLanguage': json['fromLanguage'] == null ? undefined : json['fromLanguage'],
        'toLanguage': json['toLanguage'],
    };
}

export function TranslationApiTranslateRequestToJSON(value?: TranslationApiTranslateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'text': value['text'],
        'fromLanguage': value['fromLanguage'],
        'toLanguage': value['toLanguage'],
    };
}

