/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { OCSMeta } from './OCSMeta.ts';
import {
    OCSMetaFromJSON,
    OCSMetaFromJSONTyped,
    OCSMetaToJSON,
} from './OCSMeta.ts';
import type { UnifiedSearchProvider } from './UnifiedSearchProvider.ts';
import {
    UnifiedSearchProviderFromJSON,
    UnifiedSearchProviderFromJSONTyped,
    UnifiedSearchProviderToJSON,
} from './UnifiedSearchProvider.ts';

/**
 * 
 * @export
 * @interface UnifiedSearchGetProviders200ResponseOcs
 */
export interface UnifiedSearchGetProviders200ResponseOcs {
    /**
     * 
     * @type {OCSMeta}
     * @memberof UnifiedSearchGetProviders200ResponseOcs
     */
    meta: OCSMeta;
    /**
     * 
     * @type {Array<UnifiedSearchProvider>}
     * @memberof UnifiedSearchGetProviders200ResponseOcs
     */
    data: Array<UnifiedSearchProvider>;
}

/**
 * Check if a given object implements the UnifiedSearchGetProviders200ResponseOcs interface.
 */
export function instanceOfUnifiedSearchGetProviders200ResponseOcs(value: object): value is UnifiedSearchGetProviders200ResponseOcs {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UnifiedSearchGetProviders200ResponseOcsFromJSON(json: any): UnifiedSearchGetProviders200ResponseOcs {
    return UnifiedSearchGetProviders200ResponseOcsFromJSONTyped(json, false);
}

export function UnifiedSearchGetProviders200ResponseOcsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnifiedSearchGetProviders200ResponseOcs {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': OCSMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(UnifiedSearchProviderFromJSON)),
    };
}

export function UnifiedSearchGetProviders200ResponseOcsToJSON(value?: UnifiedSearchGetProviders200ResponseOcs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'meta': OCSMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(UnifiedSearchProviderToJSON)),
    };
}

