/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface UnifiedSearchGetProvidersRequest
 */
export interface UnifiedSearchGetProvidersRequest {
    /**
     * the url the user is currently at
     * @type {string}
     * @memberof UnifiedSearchGetProvidersRequest
     */
    from?: string;
}

/**
 * Check if a given object implements the UnifiedSearchGetProvidersRequest interface.
 */
export function instanceOfUnifiedSearchGetProvidersRequest(value: object): value is UnifiedSearchGetProvidersRequest {
    return true;
}

export function UnifiedSearchGetProvidersRequestFromJSON(json: any): UnifiedSearchGetProvidersRequest {
    return UnifiedSearchGetProvidersRequestFromJSONTyped(json, false);
}

export function UnifiedSearchGetProvidersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnifiedSearchGetProvidersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : json['from'],
    };
}

export function UnifiedSearchGetProvidersRequestToJSON(value?: UnifiedSearchGetProvidersRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'],
    };
}

