/* tslint:disable */
/* eslint-disable */
/**
 * core-full
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { UnifiedSearchResultEntry } from './UnifiedSearchResultEntry.ts';
import {
    UnifiedSearchResultEntryFromJSON,
    UnifiedSearchResultEntryFromJSONTyped,
    UnifiedSearchResultEntryToJSON,
} from './UnifiedSearchResultEntry.ts';
import type { UnifiedSearchResultCursor } from './UnifiedSearchResultCursor.ts';
import {
    UnifiedSearchResultCursorFromJSON,
    UnifiedSearchResultCursorFromJSONTyped,
    UnifiedSearchResultCursorToJSON,
} from './UnifiedSearchResultCursor.ts';

/**
 * 
 * @export
 * @interface UnifiedSearchResult
 */
export interface UnifiedSearchResult {
    /**
     * 
     * @type {string}
     * @memberof UnifiedSearchResult
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof UnifiedSearchResult
     */
    isPaginated: boolean;
    /**
     * 
     * @type {Array<UnifiedSearchResultEntry>}
     * @memberof UnifiedSearchResult
     */
    entries: Array<UnifiedSearchResultEntry>;
    /**
     * 
     * @type {UnifiedSearchResultCursor}
     * @memberof UnifiedSearchResult
     */
    cursor: UnifiedSearchResultCursor | null;
}

/**
 * Check if a given object implements the UnifiedSearchResult interface.
 */
export function instanceOfUnifiedSearchResult(value: object): value is UnifiedSearchResult {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isPaginated' in value) || value['isPaginated'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    if (!('cursor' in value) || value['cursor'] === undefined) return false;
    return true;
}

export function UnifiedSearchResultFromJSON(json: any): UnifiedSearchResult {
    return UnifiedSearchResultFromJSONTyped(json, false);
}

export function UnifiedSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnifiedSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'isPaginated': json['isPaginated'],
        'entries': ((json['entries'] as Array<any>).map(UnifiedSearchResultEntryFromJSON)),
        'cursor': UnifiedSearchResultCursorFromJSON(json['cursor']),
    };
}

export function UnifiedSearchResultToJSON(value?: UnifiedSearchResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'isPaginated': value['isPaginated'],
        'entries': ((value['entries'] as Array<any>).map(UnifiedSearchResultEntryToJSON)),
        'cursor': UnifiedSearchResultCursorToJSON(value['cursor']),
    };
}

