/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { WhatsNewGet200ResponseOcs } from './WhatsNewGet200ResponseOcs.ts';
import {
    WhatsNewGet200ResponseOcsFromJSON,
    WhatsNewGet200ResponseOcsFromJSONTyped,
    WhatsNewGet200ResponseOcsToJSON,
} from './WhatsNewGet200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface WhatsNewGet200Response
 */
export interface WhatsNewGet200Response {
    /**
     * 
     * @type {WhatsNewGet200ResponseOcs}
     * @memberof WhatsNewGet200Response
     */
    ocs: WhatsNewGet200ResponseOcs;
}

/**
 * Check if a given object implements the WhatsNewGet200Response interface.
 */
export function instanceOfWhatsNewGet200Response(value: object): value is WhatsNewGet200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function WhatsNewGet200ResponseFromJSON(json: any): WhatsNewGet200Response {
    return WhatsNewGet200ResponseFromJSONTyped(json, false);
}

export function WhatsNewGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WhatsNewGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': WhatsNewGet200ResponseOcsFromJSON(json['ocs']),
    };
}

export function WhatsNewGet200ResponseToJSON(value?: WhatsNewGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': WhatsNewGet200ResponseOcsToJSON(value['ocs']),
    };
}

