/* tslint:disable */
/* eslint-disable */
/**
 * spreed
 * Chat, video & audio-conferencing using WebRTC
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.ts';
import type {
  BanUnbanActor200Response,
} from '../models/index.ts';
import {
    BanUnbanActor200ResponseFromJSON,
    BanUnbanActor200ResponseToJSON,
} from '../models/index.ts';

export interface GuestSetDisplayNameRequest {
    displayName: string;
    apiVersion: GuestSetDisplayNameApiVersionEnum;
    token: string;
    oCSAPIRequest: boolean;
}

/**
 * 
 */
export class GuestApi extends runtime.BaseAPI {

    /**
     * Set the display name as a guest
     */
    async guestSetDisplayNameRaw(requestParameters: GuestSetDisplayNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BanUnbanActor200Response>> {
        if (requestParameters['displayName'] == null) {
            throw new runtime.RequiredError(
                'displayName',
                'Required parameter "displayName" was null or undefined when calling guestSetDisplayName().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling guestSetDisplayName().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling guestSetDisplayName().'
            );
        }

        if (requestParameters['oCSAPIRequest'] == null) {
            throw new runtime.RequiredError(
                'oCSAPIRequest',
                'Required parameter "oCSAPIRequest" was null or undefined when calling guestSetDisplayName().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['displayName'] != null) {
            queryParameters['displayName'] = requestParameters['displayName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['oCSAPIRequest'] != null) {
            headerParameters['OCS-APIRequest'] = String(requestParameters['oCSAPIRequest']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ocs/v2.php/apps/spreed/api/{apiVersion}/guest/{token}/name`.replace(`{${"apiVersion"}}`, encodeURIComponent(String(requestParameters['apiVersion']))).replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BanUnbanActor200ResponseFromJSON(jsonValue));
    }

    /**
     * Set the display name as a guest
     */
    async guestSetDisplayName(requestParameters: GuestSetDisplayNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BanUnbanActor200Response> {
        const response = await this.guestSetDisplayNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GuestSetDisplayNameApiVersionEnum = {
    V1: 'v1'
} as const;
export type GuestSetDisplayNameApiVersionEnum = typeof GuestSetDisplayNameApiVersionEnum[keyof typeof GuestSetDisplayNameApiVersionEnum];
