/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.ts';
import type {
  AppPasswordGetAppPassword403Response,
} from '../models/index';
import {
    AppPasswordGetAppPassword403ResponseFromJSON,
    AppPasswordGetAppPassword403ResponseToJSON,
} from '../models/index';

export interface ProfileApiSetVisibilityRequest {
    paramId: string;
    visibility: string;
    targetUserId: string;
    oCSAPIRequest: boolean;
}

/**
 * 
 */
export class ProfileApiApi extends runtime.BaseAPI {

    /**
     * This endpoint requires password confirmation
     * Update the visibility of a parameter
     */
    async profileApiSetVisibilityRaw(requestParameters: ProfileApiSetVisibilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppPasswordGetAppPassword403Response>> {
        if (requestParameters['paramId'] == null) {
            throw new runtime.RequiredError(
                'paramId',
                'Required parameter "paramId" was null or undefined when calling profileApiSetVisibility().'
            );
        }

        if (requestParameters['visibility'] == null) {
            throw new runtime.RequiredError(
                'visibility',
                'Required parameter "visibility" was null or undefined when calling profileApiSetVisibility().'
            );
        }

        if (requestParameters['targetUserId'] == null) {
            throw new runtime.RequiredError(
                'targetUserId',
                'Required parameter "targetUserId" was null or undefined when calling profileApiSetVisibility().'
            );
        }

        if (requestParameters['oCSAPIRequest'] == null) {
            throw new runtime.RequiredError(
                'oCSAPIRequest',
                'Required parameter "oCSAPIRequest" was null or undefined when calling profileApiSetVisibility().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['paramId'] != null) {
            queryParameters['paramId'] = requestParameters['paramId'];
        }

        if (requestParameters['visibility'] != null) {
            queryParameters['visibility'] = requestParameters['visibility'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['oCSAPIRequest'] != null) {
            headerParameters['OCS-APIRequest'] = String(requestParameters['oCSAPIRequest']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ocs/v2.php/profile/{targetUserId}`.replace(`{${"targetUserId"}}`, encodeURIComponent(String(requestParameters['targetUserId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppPasswordGetAppPassword403ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint requires password confirmation
     * Update the visibility of a parameter
     */
    async profileApiSetVisibility(requestParameters: ProfileApiSetVisibilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppPasswordGetAppPassword403Response> {
        const response = await this.profileApiSetVisibilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
