/* tslint:disable */
/* eslint-disable */
/**
 * tables
 * Manage data the way you need it.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface Api1UpdateViewDataParameterOneOf1
 */
export interface Api1UpdateViewDataParameterOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof Api1UpdateViewDataParameterOneOf1
     */
    key: Api1UpdateViewDataParameterOneOf1KeyEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof Api1UpdateViewDataParameterOneOf1
     */
    value: Array<number>;
}


/**
 * @export
 */
export const Api1UpdateViewDataParameterOneOf1KeyEnum = {
    Columns: 'columns'
} as const;
export type Api1UpdateViewDataParameterOneOf1KeyEnum = typeof Api1UpdateViewDataParameterOneOf1KeyEnum[keyof typeof Api1UpdateViewDataParameterOneOf1KeyEnum];


/**
 * Check if a given object implements the Api1UpdateViewDataParameterOneOf1 interface.
 */
export function instanceOfApi1UpdateViewDataParameterOneOf1(value: object): value is Api1UpdateViewDataParameterOneOf1 {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function Api1UpdateViewDataParameterOneOf1FromJSON(json: any): Api1UpdateViewDataParameterOneOf1 {
    return Api1UpdateViewDataParameterOneOf1FromJSONTyped(json, false);
}

export function Api1UpdateViewDataParameterOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Api1UpdateViewDataParameterOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function Api1UpdateViewDataParameterOneOf1ToJSON(value?: Api1UpdateViewDataParameterOneOf1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

