/* tslint:disable */
/* eslint-disable */
/**
 * tables
 * Manage data the way you need it.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { ApiFavoriteCreate200ResponseOcs } from './ApiFavoriteCreate200ResponseOcs.ts';
import {
    ApiFavoriteCreate200ResponseOcsFromJSON,
    ApiFavoriteCreate200ResponseOcsFromJSONTyped,
    ApiFavoriteCreate200ResponseOcsToJSON,
} from './ApiFavoriteCreate200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface ApiFavoriteCreate200Response
 */
export interface ApiFavoriteCreate200Response {
    /**
     * 
     * @type {ApiFavoriteCreate200ResponseOcs}
     * @memberof ApiFavoriteCreate200Response
     */
    ocs: ApiFavoriteCreate200ResponseOcs;
}

/**
 * Check if a given object implements the ApiFavoriteCreate200Response interface.
 */
export function instanceOfApiFavoriteCreate200Response(value: object): value is ApiFavoriteCreate200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function ApiFavoriteCreate200ResponseFromJSON(json: any): ApiFavoriteCreate200Response {
    return ApiFavoriteCreate200ResponseFromJSONTyped(json, false);
}

export function ApiFavoriteCreate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiFavoriteCreate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': ApiFavoriteCreate200ResponseOcsFromJSON(json['ocs']),
    };
}

export function ApiFavoriteCreate200ResponseToJSON(value?: ApiFavoriteCreate200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': ApiFavoriteCreate200ResponseOcsToJSON(value['ocs']),
    };
}

