/* tslint:disable */
/* eslint-disable */
/**
 * tables
 * Manage data the way you need it.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { ApiTablesCreate200ResponseOcs } from './ApiTablesCreate200ResponseOcs.ts';
import {
    ApiTablesCreate200ResponseOcsFromJSON,
    ApiTablesCreate200ResponseOcsFromJSONTyped,
    ApiTablesCreate200ResponseOcsToJSON,
} from './ApiTablesCreate200ResponseOcs.ts';

/**
 * 
 * @export
 * @interface ApiTablesCreate200Response
 */
export interface ApiTablesCreate200Response {
    /**
     * 
     * @type {ApiTablesCreate200ResponseOcs}
     * @memberof ApiTablesCreate200Response
     */
    ocs: ApiTablesCreate200ResponseOcs;
}

/**
 * Check if a given object implements the ApiTablesCreate200Response interface.
 */
export function instanceOfApiTablesCreate200Response(value: object): value is ApiTablesCreate200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function ApiTablesCreate200ResponseFromJSON(json: any): ApiTablesCreate200Response {
    return ApiTablesCreate200ResponseFromJSONTyped(json, false);
}

export function ApiTablesCreate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTablesCreate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': ApiTablesCreate200ResponseOcsFromJSON(json['ocs']),
    };
}

export function ApiTablesCreate200ResponseToJSON(value?: ApiTablesCreate200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': ApiTablesCreate200ResponseOcsToJSON(value['ocs']),
    };
}

