/* tslint:disable */
/* eslint-disable */
/**
 * tables
 * Manage data the way you need it.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface ContextNavigation
 */
export interface ContextNavigation {
    /**
     * 
     * @type {number}
     * @memberof ContextNavigation
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ContextNavigation
     */
    shareId: number;
    /**
     * 
     * @type {number}
     * @memberof ContextNavigation
     */
    displayMode: number;
    /**
     * 
     * @type {string}
     * @memberof ContextNavigation
     */
    userId: string;
}

/**
 * Check if a given object implements the ContextNavigation interface.
 */
export function instanceOfContextNavigation(value: object): value is ContextNavigation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('shareId' in value) || value['shareId'] === undefined) return false;
    if (!('displayMode' in value) || value['displayMode'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ContextNavigationFromJSON(json: any): ContextNavigation {
    return ContextNavigationFromJSONTyped(json, false);
}

export function ContextNavigationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextNavigation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'shareId': json['shareId'],
        'displayMode': json['displayMode'],
        'userId': json['userId'],
    };
}

export function ContextNavigationToJSON(value?: ContextNavigation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'shareId': value['shareId'],
        'displayMode': value['displayMode'],
        'userId': value['userId'],
    };
}

