/* tslint:disable */
/* eslint-disable */
/**
 * tables
 * Manage data the way you need it.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface TableOnSharePermissions
 */
export interface TableOnSharePermissions {
    /**
     * 
     * @type {boolean}
     * @memberof TableOnSharePermissions
     */
    read: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TableOnSharePermissions
     */
    create: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TableOnSharePermissions
     */
    update: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TableOnSharePermissions
     */
    _delete: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TableOnSharePermissions
     */
    manage: boolean;
}

/**
 * Check if a given object implements the TableOnSharePermissions interface.
 */
export function instanceOfTableOnSharePermissions(value: object): value is TableOnSharePermissions {
    if (!('read' in value) || value['read'] === undefined) return false;
    if (!('create' in value) || value['create'] === undefined) return false;
    if (!('update' in value) || value['update'] === undefined) return false;
    if (!('_delete' in value) || value['_delete'] === undefined) return false;
    if (!('manage' in value) || value['manage'] === undefined) return false;
    return true;
}

export function TableOnSharePermissionsFromJSON(json: any): TableOnSharePermissions {
    return TableOnSharePermissionsFromJSONTyped(json, false);
}

export function TableOnSharePermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableOnSharePermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'read': json['read'],
        'create': json['create'],
        'update': json['update'],
        '_delete': json['delete'],
        'manage': json['manage'],
    };
}

export function TableOnSharePermissionsToJSON(value?: TableOnSharePermissions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'read': value['read'],
        'create': value['create'],
        'update': value['update'],
        'delete': value['_delete'],
        'manage': value['manage'],
    };
}

