/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { OCSMeta } from './OCSMeta.ts';
import {
    OCSMetaFromJSON,
    OCSMetaFromJSONTyped,
    OCSMetaToJSON,
} from './OCSMeta.ts';
import type { AppPasswordConfirmUserPassword200ResponseOcsData } from './AppPasswordConfirmUserPassword200ResponseOcsData.ts';
import {
    AppPasswordConfirmUserPassword200ResponseOcsDataFromJSON,
    AppPasswordConfirmUserPassword200ResponseOcsDataFromJSONTyped,
    AppPasswordConfirmUserPassword200ResponseOcsDataToJSON,
} from './AppPasswordConfirmUserPassword200ResponseOcsData.ts';

/**
 * 
 * @export
 * @interface AppPasswordConfirmUserPassword200ResponseOcs
 */
export interface AppPasswordConfirmUserPassword200ResponseOcs {
    /**
     * 
     * @type {OCSMeta}
     * @memberof AppPasswordConfirmUserPassword200ResponseOcs
     */
    meta: OCSMeta;
    /**
     * 
     * @type {AppPasswordConfirmUserPassword200ResponseOcsData}
     * @memberof AppPasswordConfirmUserPassword200ResponseOcs
     */
    data: AppPasswordConfirmUserPassword200ResponseOcsData;
}

/**
 * Check if a given object implements the AppPasswordConfirmUserPassword200ResponseOcs interface.
 */
export function instanceOfAppPasswordConfirmUserPassword200ResponseOcs(value: object): value is AppPasswordConfirmUserPassword200ResponseOcs {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AppPasswordConfirmUserPassword200ResponseOcsFromJSON(json: any): AppPasswordConfirmUserPassword200ResponseOcs {
    return AppPasswordConfirmUserPassword200ResponseOcsFromJSONTyped(json, false);
}

export function AppPasswordConfirmUserPassword200ResponseOcsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPasswordConfirmUserPassword200ResponseOcs {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': OCSMetaFromJSON(json['meta']),
        'data': AppPasswordConfirmUserPassword200ResponseOcsDataFromJSON(json['data']),
    };
}

export function AppPasswordConfirmUserPassword200ResponseOcsToJSON(value?: AppPasswordConfirmUserPassword200ResponseOcs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'meta': OCSMetaToJSON(value['meta']),
        'data': AppPasswordConfirmUserPassword200ResponseOcsDataToJSON(value['data']),
    };
}

