/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { OCSMeta } from './OCSMeta.ts';
import {
    OCSMetaFromJSON,
    OCSMetaFromJSONTyped,
    OCSMetaToJSON,
} from './OCSMeta';
import type { AutocompleteResult } from './AutocompleteResult.ts';
import {
    AutocompleteResultFromJSON,
    AutocompleteResultFromJSONTyped,
    AutocompleteResultToJSON,
} from './AutocompleteResult';

/**
 * 
 * @export
 * @interface AutoCompleteGet200ResponseOcs
 */
export interface AutoCompleteGet200ResponseOcs {
    /**
     * 
     * @type {OCSMeta}
     * @memberof AutoCompleteGet200ResponseOcs
     */
    meta: OCSMeta;
    /**
     * 
     * @type {Array<AutocompleteResult>}
     * @memberof AutoCompleteGet200ResponseOcs
     */
    data: Array<AutocompleteResult>;
}

/**
 * Check if a given object implements the AutoCompleteGet200ResponseOcs interface.
 */
export function instanceOfAutoCompleteGet200ResponseOcs(value: object): value is AutoCompleteGet200ResponseOcs {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AutoCompleteGet200ResponseOcsFromJSON(json: any): AutoCompleteGet200ResponseOcs {
    return AutoCompleteGet200ResponseOcsFromJSONTyped(json, false);
}

export function AutoCompleteGet200ResponseOcsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoCompleteGet200ResponseOcs {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': OCSMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(AutocompleteResultFromJSON)),
    };
}

export function AutoCompleteGet200ResponseOcsToJSON(value?: AutoCompleteGet200ResponseOcs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'meta': OCSMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(AutocompleteResultToJSON)),
    };
}

