/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { OCSMeta } from './OCSMeta.ts';
import {
    OCSMetaFromJSON,
    OCSMetaFromJSONTyped,
    OCSMetaToJSON,
} from './OCSMeta';
import type { Collection } from './Collection.ts';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
} from './Collection';

/**
 * 
 * @export
 * @interface CollaborationResourcesSearchCollections200ResponseOcs
 */
export interface CollaborationResourcesSearchCollections200ResponseOcs {
    /**
     * 
     * @type {OCSMeta}
     * @memberof CollaborationResourcesSearchCollections200ResponseOcs
     */
    meta: OCSMeta;
    /**
     * 
     * @type {Array<Collection>}
     * @memberof CollaborationResourcesSearchCollections200ResponseOcs
     */
    data: Array<Collection>;
}

/**
 * Check if a given object implements the CollaborationResourcesSearchCollections200ResponseOcs interface.
 */
export function instanceOfCollaborationResourcesSearchCollections200ResponseOcs(value: object): value is CollaborationResourcesSearchCollections200ResponseOcs {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CollaborationResourcesSearchCollections200ResponseOcsFromJSON(json: any): CollaborationResourcesSearchCollections200ResponseOcs {
    return CollaborationResourcesSearchCollections200ResponseOcsFromJSONTyped(json, false);
}

export function CollaborationResourcesSearchCollections200ResponseOcsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollaborationResourcesSearchCollections200ResponseOcs {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': OCSMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(CollectionFromJSON)),
    };
}

export function CollaborationResourcesSearchCollections200ResponseOcsToJSON(value?: CollaborationResourcesSearchCollections200ResponseOcs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'meta': OCSMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(CollectionToJSON)),
    };
}

