/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { NavigationGetAppsNavigation200ResponseOcs } from './NavigationGetAppsNavigation200ResponseOcs.ts';
import {
    NavigationGetAppsNavigation200ResponseOcsFromJSON,
    NavigationGetAppsNavigation200ResponseOcsFromJSONTyped,
    NavigationGetAppsNavigation200ResponseOcsToJSON,
} from './NavigationGetAppsNavigation200ResponseOcs';

/**
 * 
 * @export
 * @interface NavigationGetAppsNavigation200Response
 */
export interface NavigationGetAppsNavigation200Response {
    /**
     * 
     * @type {NavigationGetAppsNavigation200ResponseOcs}
     * @memberof NavigationGetAppsNavigation200Response
     */
    ocs: NavigationGetAppsNavigation200ResponseOcs;
}

/**
 * Check if a given object implements the NavigationGetAppsNavigation200Response interface.
 */
export function instanceOfNavigationGetAppsNavigation200Response(value: object): value is NavigationGetAppsNavigation200Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function NavigationGetAppsNavigation200ResponseFromJSON(json: any): NavigationGetAppsNavigation200Response {
    return NavigationGetAppsNavigation200ResponseFromJSONTyped(json, false);
}

export function NavigationGetAppsNavigation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NavigationGetAppsNavigation200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': NavigationGetAppsNavigation200ResponseOcsFromJSON(json['ocs']),
    };
}

export function NavigationGetAppsNavigation200ResponseToJSON(value?: NavigationGetAppsNavigation200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': NavigationGetAppsNavigation200ResponseOcsToJSON(value['ocs']),
    };
}

