/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { OCSMeta } from './OCSMeta.ts';
import {
    OCSMetaFromJSON,
    OCSMetaFromJSONTyped,
    OCSMetaToJSON,
} from './OCSMeta';
import type { OcsGetCapabilities200ResponseOcsData } from './OcsGetCapabilities200ResponseOcsData.ts';
import {
    OcsGetCapabilities200ResponseOcsDataFromJSON,
    OcsGetCapabilities200ResponseOcsDataFromJSONTyped,
    OcsGetCapabilities200ResponseOcsDataToJSON,
} from './OcsGetCapabilities200ResponseOcsData';

/**
 * 
 * @export
 * @interface OcsGetCapabilities200ResponseOcs
 */
export interface OcsGetCapabilities200ResponseOcs {
    /**
     * 
     * @type {OCSMeta}
     * @memberof OcsGetCapabilities200ResponseOcs
     */
    meta: OCSMeta;
    /**
     * 
     * @type {OcsGetCapabilities200ResponseOcsData}
     * @memberof OcsGetCapabilities200ResponseOcs
     */
    data: OcsGetCapabilities200ResponseOcsData;
}

/**
 * Check if a given object implements the OcsGetCapabilities200ResponseOcs interface.
 */
export function instanceOfOcsGetCapabilities200ResponseOcs(value: object): value is OcsGetCapabilities200ResponseOcs {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OcsGetCapabilities200ResponseOcsFromJSON(json: any): OcsGetCapabilities200ResponseOcs {
    return OcsGetCapabilities200ResponseOcsFromJSONTyped(json, false);
}

export function OcsGetCapabilities200ResponseOcsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OcsGetCapabilities200ResponseOcs {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': OCSMetaFromJSON(json['meta']),
        'data': OcsGetCapabilities200ResponseOcsDataFromJSON(json['data']),
    };
}

export function OcsGetCapabilities200ResponseOcsToJSON(value?: OcsGetCapabilities200ResponseOcs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'meta': OCSMetaToJSON(value['meta']),
        'data': OcsGetCapabilities200ResponseOcsDataToJSON(value['data']),
    };
}

