/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { TaskProcessingTask } from './TaskProcessingTask.ts';
import {
    TaskProcessingTaskFromJSON,
    TaskProcessingTaskFromJSONTyped,
    TaskProcessingTaskToJSON,
} from './TaskProcessingTask';

/**
 * 
 * @export
 * @interface TaskProcessingApiSchedule200ResponseOcsData
 */
export interface TaskProcessingApiSchedule200ResponseOcsData {
    /**
     * 
     * @type {TaskProcessingTask}
     * @memberof TaskProcessingApiSchedule200ResponseOcsData
     */
    task: TaskProcessingTask;
}

/**
 * Check if a given object implements the TaskProcessingApiSchedule200ResponseOcsData interface.
 */
export function instanceOfTaskProcessingApiSchedule200ResponseOcsData(value: object): value is TaskProcessingApiSchedule200ResponseOcsData {
    if (!('task' in value) || value['task'] === undefined) return false;
    return true;
}

export function TaskProcessingApiSchedule200ResponseOcsDataFromJSON(json: any): TaskProcessingApiSchedule200ResponseOcsData {
    return TaskProcessingApiSchedule200ResponseOcsDataFromJSONTyped(json, false);
}

export function TaskProcessingApiSchedule200ResponseOcsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProcessingApiSchedule200ResponseOcsData {
    if (json == null) {
        return json;
    }
    return {
        
        'task': TaskProcessingTaskFromJSON(json['task']),
    };
}

export function TaskProcessingApiSchedule200ResponseOcsDataToJSON(value?: TaskProcessingApiSchedule200ResponseOcsData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'task': TaskProcessingTaskToJSON(value['task']),
    };
}

