/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { TextProcessingTask } from './TextProcessingTask.ts';
import {
    TextProcessingTaskFromJSON,
    TextProcessingTaskFromJSONTyped,
    TextProcessingTaskToJSON,
} from './TextProcessingTask.ts';

/**
 * 
 * @export
 * @interface TextProcessingApiListTasksByApp200ResponseOcsData
 */
export interface TextProcessingApiListTasksByApp200ResponseOcsData {
    /**
     * 
     * @type {Array<TextProcessingTask>}
     * @memberof TextProcessingApiListTasksByApp200ResponseOcsData
     */
    tasks: Array<TextProcessingTask>;
}

/**
 * Check if a given object implements the TextProcessingApiListTasksByApp200ResponseOcsData interface.
 */
export function instanceOfTextProcessingApiListTasksByApp200ResponseOcsData(value: object): value is TextProcessingApiListTasksByApp200ResponseOcsData {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    return true;
}

export function TextProcessingApiListTasksByApp200ResponseOcsDataFromJSON(json: any): TextProcessingApiListTasksByApp200ResponseOcsData {
    return TextProcessingApiListTasksByApp200ResponseOcsDataFromJSONTyped(json, false);
}

export function TextProcessingApiListTasksByApp200ResponseOcsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextProcessingApiListTasksByApp200ResponseOcsData {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(TextProcessingTaskFromJSON)),
    };
}

export function TextProcessingApiListTasksByApp200ResponseOcsDataToJSON(value?: TextProcessingApiListTasksByApp200ResponseOcsData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(TextProcessingTaskToJSON)),
    };
}

