/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { TranslationApiTranslate400ResponseOcs } from './TranslationApiTranslate400ResponseOcs.ts';
import {
    TranslationApiTranslate400ResponseOcsFromJSON,
    TranslationApiTranslate400ResponseOcsFromJSONTyped,
    TranslationApiTranslate400ResponseOcsToJSON,
} from './TranslationApiTranslate400ResponseOcs.ts';

/**
 * 
 * @export
 * @interface TranslationApiTranslate400Response
 */
export interface TranslationApiTranslate400Response {
    /**
     * 
     * @type {TranslationApiTranslate400ResponseOcs}
     * @memberof TranslationApiTranslate400Response
     */
    ocs: TranslationApiTranslate400ResponseOcs;
}

/**
 * Check if a given object implements the TranslationApiTranslate400Response interface.
 */
export function instanceOfTranslationApiTranslate400Response(value: object): value is TranslationApiTranslate400Response {
    if (!('ocs' in value) || value['ocs'] === undefined) return false;
    return true;
}

export function TranslationApiTranslate400ResponseFromJSON(json: any): TranslationApiTranslate400Response {
    return TranslationApiTranslate400ResponseFromJSONTyped(json, false);
}

export function TranslationApiTranslate400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslationApiTranslate400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ocs': TranslationApiTranslate400ResponseOcsFromJSON(json['ocs']),
    };
}

export function TranslationApiTranslate400ResponseToJSON(value?: TranslationApiTranslate400Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ocs': TranslationApiTranslate400ResponseOcsToJSON(value['ocs']),
    };
}

