/* tslint:disable */
/* eslint-disable */
/**
 * core
 * Core functionality of Nextcloud
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { WhatsNewGet200ResponseOcsDataWhatsNew } from './WhatsNewGet200ResponseOcsDataWhatsNew.ts';
import {
    WhatsNewGet200ResponseOcsDataWhatsNewFromJSON,
    WhatsNewGet200ResponseOcsDataWhatsNewFromJSONTyped,
    WhatsNewGet200ResponseOcsDataWhatsNewToJSON,
} from './WhatsNewGet200ResponseOcsDataWhatsNew';

/**
 * 
 * @export
 * @interface WhatsNewGet200ResponseOcsData
 */
export interface WhatsNewGet200ResponseOcsData {
    /**
     * 
     * @type {string}
     * @memberof WhatsNewGet200ResponseOcsData
     */
    changelogURL: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsNewGet200ResponseOcsData
     */
    product: string;
    /**
     * 
     * @type {string}
     * @memberof WhatsNewGet200ResponseOcsData
     */
    version: string;
    /**
     * 
     * @type {WhatsNewGet200ResponseOcsDataWhatsNew}
     * @memberof WhatsNewGet200ResponseOcsData
     */
    whatsNew?: WhatsNewGet200ResponseOcsDataWhatsNew;
}

/**
 * Check if a given object implements the WhatsNewGet200ResponseOcsData interface.
 */
export function instanceOfWhatsNewGet200ResponseOcsData(value: object): value is WhatsNewGet200ResponseOcsData {
    if (!('changelogURL' in value) || value['changelogURL'] === undefined) return false;
    if (!('product' in value) || value['product'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function WhatsNewGet200ResponseOcsDataFromJSON(json: any): WhatsNewGet200ResponseOcsData {
    return WhatsNewGet200ResponseOcsDataFromJSONTyped(json, false);
}

export function WhatsNewGet200ResponseOcsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WhatsNewGet200ResponseOcsData {
    if (json == null) {
        return json;
    }
    return {
        
        'changelogURL': json['changelogURL'],
        'product': json['product'],
        'version': json['version'],
        'whatsNew': json['whatsNew'] == null ? undefined : WhatsNewGet200ResponseOcsDataWhatsNewFromJSON(json['whatsNew']),
    };
}

export function WhatsNewGet200ResponseOcsDataToJSON(value?: WhatsNewGet200ResponseOcsData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'changelogURL': value['changelogURL'],
        'product': value['product'],
        'version': value['version'],
        'whatsNew': WhatsNewGet200ResponseOcsDataWhatsNewToJSON(value['whatsNew']),
    };
}

